# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: dotnet version
      uses: Azure/powershell@v1
      with:
        inlineScript: dotnet --version
        azPSVersion: latest
        
    - name: build.ps1
      uses: Azure/powershell@v1
      with:
        # Specify the Az PowerShell script here.
        inlineScript: ./build.ps1
        # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
        azPSVersion: latest
        # Select the value of the ErrorActionPreference variable for executing the script. Options: stop, continue, silentlyContinue. Default is Stop.
#         errorActionPreference: # optional, default is Stop
        # If this is true, this task will fail if any errors are written to the error pipeline, or if any data is written to the Standard Error stream.
#         failOnStandardError: # optional, default is false
